### PR TITLE
dec: improve coefficient implementation

### PR DESCRIPTION
**Pull request by sploiselle**
@benesch This is maybe more appropriate as a draft, but whatever. Very much not used to writing performance-sensitive code, so tried to not do things that made my microbenchmarks worse––but would be very glad for any insights or obnoxious over-optimizations you'd like to see. e.g. this code could be macro-ized with some more looping and multiplication, but that felt counter-productive.

### CODE REVIEW

**Review by benesch — APPROVED** [review]
TBH I'm kind of psyched it's not macro-ized. It's more typing but so easy to follow like this. I'm not going to pretend that I grok the algorithm in its full detail, but seems pretty reasonable on a quick glance. Delighted you got this all working!

Where do your microbenchmarks live? In Materialize? Would they be easy to import here?

**Comment by sploiselle** [comment]
@benesch Oh sorry, I wound up removing the benchmarks because `#[feature(test)]` prevented the library from building on Ubuntu, which seems to use `stable`. How would you recommend getting them into the test suite?

**Comment by benesch** [comment]
Oh! Use the criterion crate instead. It’s a bit harder to set up but gives nicer output, and it works on stable.

**Comment by benesch** [comment]
Here's an example: https://github.com/MaterializeInc/materialize/blob/main/src/repr/benches/row.rs

**Review by benesch — APPROVED** [review]
Still LGTM! Thanks for adding the benchmarks!

**Pull request merged**
